spring:
  application:
    name: Dental-House

# Datasource Configurations
  datasource:
    url: jdbc:mysql://localhost:3306/dental_house_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# Server configurations
server:
  port: 8080

# Additional Configurations
app:
  base_url: /api/v1
  jwt:
    secret: ${jwt.secret}
    token_expiry:
        access_seconds: 3600
        refresh_seconds: 1296000